# Generated by Django 3.0.6 on 2020-06-08 10:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="team_members",
            field=models.IntegerField(validators=[users.models.validate_team_members]),
        ),
    ]
