# Generated by Django 3.0.6 on 2020-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_myuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="continent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Asia", "Asia"),
                    ("America", "America"),
                    ("Europe", "Europe"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="myuser",
            name="country_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="myuser",
            name="flag",
            field=models.ImageField(blank=True, null=True, upload_to="flags"),
        ),
    ]
