# Generated by Django 3.0.6 on 2020-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20200621_1407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="flag",
            field=models.ImageField(blank=True, null=True, upload_to="flags/"),
        ),
    ]
