# Generated by Django 3.0.6 on 2020-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20200621_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="flag",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
