# Generated by Django 3.0.6 on 2020-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20200621_1751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="flag",
            field=models.ImageField(blank=True, null=True, upload_to="flags/"),
        ),
    ]
