# Generated by Django 3.0.6 on 2020-06-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_trade"),
    ]

    operations = [
        migrations.AlterModelOptions(name="resource", options={"ordering": ["GDP"]},),
    ]
