# Generated by Django 3.0.6 on 2020-06-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_auto_20200621_1407"),
    ]

    operations = [
        migrations.AlterModelOptions(name="resource", options={"ordering": ["-GDP"]},),
    ]
