# Generated by Django 3.0.6 on 2020-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0005_auto_20200621_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="rate_food",
            field=models.DecimalField(
                decimal_places=2, default=0.17, max_digits=4, verbose_name="rate_food"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="rate_medicine",
            field=models.DecimalField(
                decimal_places=2,
                default=0.08,
                max_digits=4,
                verbose_name="rate_medicine",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="rate_mscb",
            field=models.DecimalField(
                decimal_places=2, default=0.14, max_digits=4, verbose_name="rate_mscb"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="rate_technology",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                verbose_name="rate_technology",
            ),
        ),
    ]
