# Generated by Django 3.0.6 on 2020-06-27 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("panel", "0006_auto_20200625_2138"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("update_no", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("America", "America"),
                            ("Global", "Global"),
                        ],
                        max_length=10,
                    ),
                ),
                ("update", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="question/"),
                ),
                ("question", models.TextField()),
                ("pdf", models.FileField(blank=True, null=True, upload_to="files")),
                ("answer", models.CharField(max_length=40)),
                (
                    "rate_mscb",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "rate_food",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "rate_technology",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "rate_medicine",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission", models.CharField(max_length=40)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("isCorrect", models.BooleanField(default=False)),
                (
                    "additional_rate_mscBits",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "additional_rate_food",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "additional_rate_technology",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "additional_rate_medicine",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="panel.Question"
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
