# Generated by Django 3.0.6 on 2020-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0007_question_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notifications", models.CharField(max_length=100)),
            ],
        ),
    ]
