# Generated by Django 3.0.6 on 2020-06-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0008_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="notifications",
            new_name="notification",
        ),
    ]
