# Generated by Django 3.0.6 on 2020-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0009_auto_20200628_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="pdf",
            field=models.URLField(blank=True, null=True),
        ),
    ]
